services:
  api:
    build:
      context: ./api
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_DATABASE=${NEO4J_DATABASE}
      - SUPPORT_NEO4J_URI=${SUPPORT_NEO4J_URI}
      - SUPPORT_NEO4J_PASSWORD=${SUPPORT_NEO4J_PASSWORD}
      - SUPPORT_NEO4J_USERNAME=${SUPPORT_NEO4J_USERNAME}
      - SUPPORT_NEO4J_DATABASE=${SUPPORT_NEO4J_DATABASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - net
    x-develop:
      watch:
        - action: rebuild
          path: ./api
    ports:
      - 8080:8080
  ui:
    build:
      context: ./ui
    environment:
      - ADVERTISED_ADDRESS=${ADVERTISED_ADDRESS}
    networks:
      - net
    x-develop:
      watch:
        - action: rebuild
          path: ./ui
    ports:
      - 8501:8501
networks:
  net: